### ISSUE TITLE
Move log files to the wiki

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/glm-parser#37]
Remove all the log files from master and all branches and move them into the wiki git for this repo.

**Comment by Travelinglight** [comment]
Should we also use a common format of log? If every write log differently, it is difficult to generate a table using script.

**Comment by avacariu** [comment]
Maybe there can be a flag so that when `glm_parser.py` finishes, it can print out (after the existing output) the exact stuff we want to store in the log files. It sort of already does that, but it's not very consistent.

If it were to print out YAML like
```yaml
machine: rcg-hadoop
commit: 8c8c5a751329ebd84c0a6db574fca16d22a6e3bc
timestamp: 2016-06-16T16:45:20.938779
accuracy:
    unlabeled: 0.865941551834
    unlabeled-attachment: 0.871303458342
training-time: 2981.04236698
```

Then whoever is running it can just copy & paste it into a log file, and then it'd be trivial to parse using PyYAML.
